apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-project
  name: jenkins-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-project
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins-project
    spec:
      containers:
      - image: jenkins-project
        name: jenkins-project
        resources: {}
status: {}
