apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-project
  name: jenkins-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-project
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins-project
    spec:
      containers:
      - name: jenkins-project
        image: nginx  # Just default image, pipeline will change it
        ports: 
          - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
