apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-project-deployment
  name: jenkins-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-project
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins-project
    spec:
      containers:
      - image: nginx  # Just default image, pipeline will change it
        name: jenkins-project
        ports: 
          - containerPort: 80
        resources: {}
status: {}
