apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOYMENT}
  template:
    metadata:
      labels:
        app: ${DEPLOYMENT}
    spec:
      containers:
      - name: ${CONTAINER}
        image: ${IMAGE}:${TAG}
        volumeMounts:
        - name: harbor-ca-cert
          mountPath: /usr/local/share/ca-certificates/harbor-ca.crt 
          subPath: ca.crt
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
      volumes:
        - name: harbor-ca-cert
          secret:
            secretName: harbor-ca-cert
